import { Inter, Poppins, Roboto } from "next/font/google";
import "./globals.css";
import Header from "./components/common/header/Header";
import Footer from "./components/common/Footer";

const inter = Inter({
  variable:"--font-inter",
  subsets:["latin"]
})

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${poppins.variable} ${roboto.variable} antialiased scroll-smooth`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
